export const COMPETENCIES: string[] = [
  "Computer Basics",
  "Operating Systems",
  "File Management",
  "Web Browsing",
  "Online Safety",
  "Email & Communication",
  "Word Processing",
  "Spreadsheets",
  "Presentations",
  "Databases",
  "Collaboration Tools",
  "Cloud Services",
  "Cybersecurity Basics",
  "Privacy & Data Protection",
  "Digital Citizenship",
  "Search & Information Literacy",
  "Social Media",
  "Coding Fundamentals",
  "Networking Basics",
  "Hardware & Peripherals",
  "Troubleshooting",
  "Accessibility & Inclusive Design",
]
